apiVersion: argoproj.io/v1alpha1   
kind: Application                 
metadata:
  name: pgstay-frontend           
  namespace: argocd 
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=tanmay678/pgstay-frontend:latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest 
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: values.yml           
spec:
  project: pgstay   
  source:
    repoURL: https://github.com/Tanmay-008/k3s-cluster.git
    targetRevision: main
    path: projects/pgstay/frontend
    helm:
      valueFiles:
        - values.yml
        - secrets://pgstay-frontend-secret-encrypted.yml
  destination:
    server: https://kubernetes.default.svc 
    namespace: pgstay             
  syncPolicy:                      
    automated:                     
      prune: true                  
      selfHeal: true  
    syncOptions: 
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true