apiVersion: argoproj.io/v1alpha1   
kind: Application                 
metadata:
  name: room-service           
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: room-service=tanmay678/pgstay-room-service
    argocd-image-updater.argoproj.io/room-service.update-strategy: semver
    argocd-image-updater.argoproj.io/room-service.allowed-tags: "regexp:^1\\.0\\.[0-9]+$"
    argocd-image-updater.argoproj.io/room-service.helm.image-tag: k3s-apps-chart.image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:values.yml"
                
spec:
  project: pgstay   
  sources:
   - repoURL: https://github.com/Tanmay-008/k3s-cluster.git
     targetRevision: main
     path: projects/pgstay/room-service
     helm:
       valueFiles:
         - values.yml
         - secrets://room-service-secret-encrypted.yaml
  destination:
    server: https://kubernetes.default.svc 
    namespace: pgstay             
  syncPolicy:                      
    automated:                     
      prune: true                  
      selfHeal: true  
    syncOptions: 
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true