apiVersion: argoproj.io/v1alpha1   
kind: Application                 
metadata:
  name: url-shortener-frontend           
  namespace: argocd 
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=tanmay678/url-shortener-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.allowed-tags: "regexp:^1\\.0\\.[0-9]+$"
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: k3s-apps-chart.image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:values.yml"
spec:
  project: default   
  source:
    repoURL: https://github.com/Tanmay-008/k3s-cluster.git
    targetRevision: main
    path: projects/url-shortener/frontend
    helm:
      valueFiles:
        - values.yaml
        - secrets://frontend-secret-encrypted.yaml
  destination:
    server: https://kubernetes.default.svc 
    namespace: url-shortener             
  syncPolicy:                      
    automated:                     
      prune: true                  
      selfHeal: true  
    syncOptions: 
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true