apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k6-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/grafana/k6-operator'
      chart: k6-operator
      targetRevision: 4.6.0
      helm:
        valueFiles:
          - $values/projects/grafana/grafana-k6-operator.yaml
          
    - repoURL: 'https://github.com/Tanmay-008/k3s-cluster.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true